import type { Metadata } from "next";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.css'
// import { useEffect } from "react";
import Nav from "./component/navigationBar/nav";
import Footer from "./component/footer/footer";
import Top from "./component/back_top/top";
import Spinner from "./component/spinner/spinner";

// G S A P

import { gsap } from "gsap";    
import { Flip } from "gsap/Flip";
import { ScrollTrigger } from "gsap/ScrollTrigger";


gsap.registerPlugin(Flip,ScrollTrigger);


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // useEffect(() => {
  //   import("bootstrap/dist/js/bootstrap");
  // }, []);


  return (
    <html lang="en">
      <head>     

      </head>
      <body>
        <Nav />
        <Spinner />
        {children}
        <Top /> 
        <Footer />


       



      </body>
    </html>
  );
}
